ecommerce_3/apps/urls.py
from django.urls import path
from .views import *

app_name = "apps"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart")
]

ecommerce_3/ecommerce_3/urls.py
from django.apps import apps
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.urls")),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_3/apps/models.py
from distutils.command.upload import upload
import email
from email.mime import image
from ntpath import join
from turtle import title
from unicodedata import category
from django import views
from django.db import models
from django.contrib.auth.models import User
from django.forms import model_to_dict

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveBigIntegerField()
    selling_price = models.PositiveBigIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.title

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveBigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart " + str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Complated", "Order Complated"),
    ("Order Canceled", "Order Canceled"),
    
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return "Order: " + str(self.id)

ecommerce_3/apps/views.py
from itertools import product
from multiprocessing import context
from re import template
import this
from django.shortcuts import render
from django.views.generic import TemplateView

from apps.models import Cart, CartProduct, Category, Product

# Create your views here.

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myname'] = "Babayew Eziz"
        context['product_list'] = Product.objects.all()
        context["product_list"] = Product.objects.all().order_by("-id")
        # context['allcategories'] = Category.objects.all()
        return context


class AllProductsView(TemplateView):
    template_name = "allproducts.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all()
        return context

class ProductDetailView(TemplateView):
    template_name = "productdetail.html"

    def get_context_data(self, **kwargs):
        context = super(). get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context['product'] = product
        return context


class AddToCartView(TemplateView):
    template_name = "addtocart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #get product id from requested url
        #talap edilýän url-dan önüm id-ini alyň
        product_id = self.kwargs['pro_id']
        

        #get product
        #önüm al
        product_obj = Product.objects.get(id=product_id)



        #check if cart exists
        #sebediň bardygyny ýa-da ýokdugyny barlaň
    
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product=product_obj)

            #item already exiists in cart
            #sebetde eýýäm bar

            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()

            #new item is added in cart
            #sebede täze zat goşuldy
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
            
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()

        #check if product already exists in cart.
        #sebetde önümiň bardygyny ýa-da ýokdugyny barlaň.

        return context


class AboutView(TemplateView):
    template_name = "about.html"


class ContactView(TemplateView):
    template_name = "contact.html"

ecommerce_3/templates/about.html
{% extends 'base.html' %}

{% block title %}About us{% endblock %}

{% block content %}
    <p>About</p>
{% endblock %}

ecommerce_3/templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>  <!--Sebede üstünlikli goşuldy.-->
</div>
{% endblock %}

ecommerce_3/templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Products</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3" style="border: 1px solid rgb(16, 2, 141);">
            <div class="m-4">
                <h4><a href="{% url 'apps:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                <p class="mt-3">Price: <strike>TMT: {{p.marked_price}}</strike> TMT: {{p.selling_price}}</p>
                <a href="{% url 'apps:addtocart' p.id %}" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

ecommerce_3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <a href="{% url 'apps:home' %}">Home</a>
    <a href="{% url 'apps:about' %}">About us</a>
    <a href="{% url 'apps:contact' %}">Contact us</a>
    <a href="{% url 'apps:allproducts' %}">Categories</a>

    <hr>

    {% block content %}
    {% endblock %}

</body> 
</html>

ecommerce_3/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact us{% endblock %}

{% block content %}
    <h1>Contact us</h1>
    <h1>+99361843349</h1>
{% endblock %}

ecommerce_3/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">Salam Eziz</h1>
    <hr>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3" style="border: 1px solid rgb(16, 2, 141);">
            <div class="m-3">

                <h3>{{p.title}}</h3>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                <p class="mt-3">Price: <strike>TMT: {{p.marked_price}}</strike> TMT: {{p.selling_price}}</p>
                <a href="" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce_3/templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" class="img-fuild">
        </div>
        <div class="col-md-6">
            <h4>{{product.title}} (Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>TMT: {{product.marked_price}} </strike>TMT: {{product.selling_price}}</h5>
            <a href="{% url 'apps:addtocart' product.id %}" class="btn btn-info">Add To Card</a>
            <hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info">Return Policy: {{product.return_policy}}</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}